"""Generate src/data/features.generated.js from the source spreadsheet.

Run:  python3 scripts/extract-features.py
The 51 feature strings are never retyped by hand; this is their only transcription.
"""
import json
import re

import openpyxl

SRC = "source-data/2nd_year_EA_Applications_1.xlsx"
OUT = "src/data/features.generated.js"
TARGET = "Environmental and Natural resource Mapping Application"

# Spreadsheet module name -> the id used throughout the portal.
IDS = {
    "Environmental and Climate Mapping": "climate",
    "Water Resources Mapping": "water",
    "Parks and Tourism Management": "parks",
    "Conservation Management": "conservation",
    "Forestry Resources Mapping": "forestry",
    "Mining Sites Mapping": "mining",
}

ws = openpyxl.load_workbook(SRC, data_only=True).active
app = module = None
features = {}

for row in ws.iter_rows(min_row=2, values_only=True):
    if row[1]:
        app = row[1]
    if row[2]:
        module = row[2]
    if app != TARGET or not row[5]:
        continue
    features[IDS[module]] = [
        re.sub(r"^\d+\.\s*", "", line).strip()
        for line in str(row[5]).split("\n")
        if line.strip()
    ]

total = sum(len(v) for v in features.values())
assert len(features) == 6, f"expected 6 modules, got {len(features)}"
assert total == 51, f"expected 51 features, got {total}"

body = ",\n".join(
    f"  {k}: " + json.dumps(v, indent=2, ensure_ascii=False).replace("\n", "\n  ")
    for k, v in features.items()
)

with open(OUT, "w") as f:
    f.write(
        "// GENERATED by scripts/extract-features.py - do not edit by hand.\n"
        f"// Source: {SRC}\n"
        f"// {len(features)} modules, {total} features.\n\n"
        "export const features = {\n" + body + ",\n}\n"
    )

print(f"wrote {OUT}: {len(features)} modules, {total} features")
