"""Convert client photography to responsive WebP for the portal.

Run once after changing any photograph:  python3 scripts/prepare-images.py
Outputs are committed; the client never needs to run this.
"""
import json
import os
from PIL import Image, ImageFilter

SRC_SHOTS = os.path.expanduser("~/Pictures/Screenshots")
SRC_DL = os.path.expanduser("~/Downloads")
OUT = "public/images"

# slug -> (source file, crop bias)
# Crop bias picks which part of the frame survives a wide crop:
#   "sky"    keeps the upper third   "center" keeps the middle
SOURCES = {
    "hero-1":              (f"{SRC_SHOTS}/environment1.jpg", "center"),
    "hero-2":              (f"{SRC_SHOTS}/water resource4.jpg", "center"),
    "hero-3":              (f"{SRC_SHOTS}/conservation1.jpg", "center"),
    "climate-card":        (f"{SRC_SHOTS}/environment1.jpg", "sky"),
    "climate-hero":        (f"{SRC_SHOTS}/environment1.jpg", "center"),
    "water-card":          (f"{SRC_SHOTS}/water resource4.jpg", "center"),
    "water-hero":          (f"{SRC_SHOTS}/water resources1.jpg", "center"),
    "parks-card":          (f"{SRC_SHOTS}/tourism.jpg", "center"),
    "parks-hero":          (f"{SRC_SHOTS}/tourism3.jpg", "center"),
    "conservation-card":   (f"{SRC_SHOTS}/conservation3.jpg", "center"),
    "conservation-hero":   (f"{SRC_SHOTS}/conservation2.jpg", "center"),
    "forestry-card":       (f"{SRC_DL}/forestry-canopy.jpg", "center"),
    "forestry-hero":       (f"{SRC_DL}/forestry-canopywalk.jpg", "center"),
    "mining-card":         (f"{SRC_SHOTS}/mining1.jpg", "center"),
    "mining-hero":         (f"{SRC_SHOTS}/mining2.jpg", "center"),
    "adaptation-card":     (f"{SRC_DL}/nathan-cima-KmcWyQO4hgA-unsplash.jpg", "center"),
    "adaptation-hero":     (f"{SRC_DL}/nathan-cima-KmcWyQO4hgA-unsplash.jpg", "center"),
}

# Forestry sources are 960x600; encoding above 1280 invents no detail.
CAPPED = {"forestry-card", "forestry-hero"}
WIDTHS = [640, 1280, 1920]


def crop_to(im, ratio, bias):
    w, h = im.size
    target_h = int(w / ratio)
    if target_h <= h:
        top = 0 if bias == "sky" else (h - target_h) // 2
        return im.crop((0, top, w, top + target_h))
    target_w = int(h * ratio)
    left = (w - target_w) // 2
    return im.crop((left, 0, left + target_w, h))


def main():
    os.makedirs(OUT, exist_ok=True)
    total = 0
    emitted = {}
    for slug, (path, bias) in SOURCES.items():
        if not os.path.exists(path):
            raise SystemExit(f"missing source: {path}")
        im = Image.open(path).convert("RGB")
        ratio = 16 / 9 if "hero" in slug else 3 / 2
        im = crop_to(im, ratio, bias)

        # Never upscale: a width wider than the cropped source is skipped.
        # What actually gets written is recorded in the manifest, so the
        # front end can never point at a file that was not produced.
        # Cards never render above ~845 CSS px (sizes: 33vw at 2560), so a
        # 1920 tier is only ever selected by ultra-wide high-DPI viewports and
        # costs ~1.7 MB for a density gain invisible on photographs. Full-bleed
        # heroes keep 1920.
        widths = [w for w in WIDTHS if not (slug in CAPPED and w > 1280)]
        if slug.endswith("-card"):
            widths = [w for w in widths if w <= 1280]
        widths = [w for w in widths if w <= im.width]
        if not widths:
            widths = [im.width]
        for w in widths:
            out = im.resize((w, int(w / ratio)), Image.LANCZOS)
            f = f"{OUT}/{slug}-{w}.webp"
            out.save(f, "WEBP", quality=82, method=6)
            total += os.path.getsize(f)
        emitted[slug] = widths

        lqip = im.resize((20, int(20 / ratio)), Image.LANCZOS)
        lqip = lqip.filter(ImageFilter.GaussianBlur(1))
        f = f"{OUT}/{slug}-lqip.webp"
        lqip.save(f, "WEBP", quality=40)
        total += os.path.getsize(f)
        print(f"  {slug:22} {im.width}x{im.height} -> {widths}")

    # Single source of truth for which widths exist. src/config/images.js
    # reads this rather than recomputing the rule and drifting from it.
    with open("src/config/image-manifest.js", "w") as f:
        f.write(
            "// GENERATED by scripts/prepare-images.py - do not edit by hand.\n"
            "export const manifest = " + json.dumps(emitted, indent=2) + "\n"
        )
    print(f"  wrote src/config/image-manifest.js ({len(emitted)} slugs)")

    # What a browser actually downloads on first paint. srcset means only one
    # width per image is ever fetched, so total-on-disk is not transfer weight.
    first_paint = os.path.getsize(f"{OUT}/hero-1-1920.webp")
    for slug in SOURCES:
        if slug.endswith("-card"):
            first_paint += os.path.getsize(f"{OUT}/{slug}-640.webp")
        first_paint += os.path.getsize(f"{OUT}/{slug}-lqip.webp")

    mb = total / 1e6
    fp_kb = first_paint / 1024
    print(f"\ntotal on disk {mb:.2f} MB across all widths")
    print(f"first-paint transfer {fp_kb:.0f} KB (eager hero + 6 cards at 640 + placeholders)")
    if fp_kb > 1024:
        raise SystemExit(f"FAIL: first paint {fp_kb:.0f} KB exceeds 1024 KB")
    if mb > 7.0:
        raise SystemExit(f"FAIL: disk total {mb:.2f} MB exceeds 7.0 MB sanity ceiling")
    print("PASS: first paint within 1 MB, disk total within ceiling")


if __name__ == "__main__":
    main()
